-- MySQL Script generated by MySQL Workbench
-- Fri Nov 21 10:50:44 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `id` INT NOT NULL,
  `zip` INT NOT NULL,
  `state` VARCHAR(45) NULL,
  `neighborhood` VARCHAR(45) NULL,
  PRIMARY KEY (`zip`, `id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`house`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`house` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`house` (
  `id` INT NOT NULL,
  `number` INT NULL,
  `street` VARCHAR(45) NULL,
  `apt` VARCHAR(45) NULL,
  `address_zip` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_House_address_idx` (`address_zip` ASC),
  CONSTRAINT `fk_House_address`
    FOREIGN KEY (`address_zip`)
    REFERENCES `mydb`.`address` (`zip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`crime_three`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crime_three` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`crime_three` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `address_zip` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_crime_three_address1_idx` (`address_zip` ASC),
  CONSTRAINT `fk_crime_three_address1`
    FOREIGN KEY (`address_zip`)
    REFERENCES `mydb`.`address` (`zip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`crime_nine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crime_nine` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`crime_nine` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `address_zip` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_crime_nine_address1_idx` (`address_zip` ASC),
  CONSTRAINT `fk_crime_nine_address1`
    FOREIGN KEY (`address_zip`)
    REFERENCES `mydb`.`address` (`zip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`school`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`school` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`school` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `number` INT NULL,
  `street` VARCHAR(45) NULL,
  `address_zip` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_school_address1_idx` (`address_zip` ASC),
  CONSTRAINT `fk_school_address1`
    FOREIGN KEY (`address_zip`)
    REFERENCES `mydb`.`address` (`zip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`price` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`price` (
  `id` INT NOT NULL,
  `price` VARCHAR(45) NULL,
  `house_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_price_house1_idx` (`house_id` ASC),
  CONSTRAINT `fk_price_house1`
    FOREIGN KEY (`house_id`)
    REFERENCES `mydb`.`house` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
